apiVersion: v1
kind: Service
metadata:
  name: backendservice
  labels:
    app: backendservice
spec:
  type: NodePort
  selector:
    matchLabels:
      app: backend
  ports:
    - port: 8080
      targetPort: 8080
        # place cluster ip here: 

