apiVersion: v1
kind: Pod
metadata:
  name: mono
  labels:
    app: springpod
spec:
  containers:
    - name: spring
      image: cazzzzz/mono-withstage:latest
      ports:
        - containerPort: 8080

